using Compilador.WebApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.IO;

namespace Compilador.WebApp.Controllers
{
    public class AnalisadorController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GetFile(IFormFile FileFullPath, string fullText)
        {
            var filePath = Path.GetTempFileName();

            if(FileFullPath != null)
            {
                using (var stream = System.IO.File.Create(filePath))
                {
                    // The formFile is the method parameter which type is IFormFile
                    // Saves the files to the local file system using a file name generated by the app.
                    FileFullPath.CopyTo(stream);
                }

            }

            FileViewModel data = new FileViewModel()
            {
                FileFullPath = filePath,
            };

            return RedirectToAction("LerCodigo", "LerArquivo", data);
        }
    }
}
